const fs = require('fs');
const path = 'c:/Users/hanis/Desktop/yoimedia/flowx/src/pages/leads/Leads.jsx';
const content = fs.readFileSync(path, 'utf8');
const lines = content.split(/\r?\n/);
const truncated = lines.slice(0, 1295);

const modalCode = [
    '        </div>',
    '',
    '            {/* ── SCHEDULE MEET MODAL ── */}',
    '            {showMeetModal && meetLead && (',
    '                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">',
    '                    <div className="bg-white rounded-3xl shadow-2xl w-full max-w-lg overflow-hidden border border-slate-100">',
    '                        {/* Header */}',
    '                        <div className="px-6 pt-5 pb-4 border-b border-slate-100 flex items-center justify-between">',
    '                            <div className="flex items-center gap-3">',
    '                                <div className="w-9 h-9 rounded-xl bg-emerald-100 flex items-center justify-center">',
    '                                    <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">',
    '                                        <path strokeLinecap="round" strokeLinejoin="round" d="M15 10l4.553-2.069A1 1 0 0121 8.82v6.36a1 1 0 01-1.447.894L15 14M4 8a2 2 0 012-2h9a2 2 0 012 2v8a2 2 0 01-2 2H6a2 2 0 01-2-2V8z" />',
    '                                    </svg>',
    '                                </div>',
    '                                <div>',
    '                                    <h2 className="text-base font-black text-slate-900">Schedule Google Meet</h2>',
    '                                    <p className="text-xs text-slate-400 font-medium mt-0.5 flex items-center gap-1.5">',
    '                                        {meetLead.name}',
    '                                        <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold ${(STATUS_CONFIG[meetLead.status] || STATUS_CONFIG.new).bg} ${(STATUS_CONFIG[meetLead.status] || STATUS_CONFIG.new).text}`}>',
    '                                            <span className={`w-1.5 h-1.5 rounded-full ${(STATUS_CONFIG[meetLead.status] || STATUS_CONFIG.new).dot}`} />',
    '                                            {(STATUS_CONFIG[meetLead.status] || STATUS_CONFIG.new).label}',
    '                                        </span>',
    '                                    </p>',
    '                                </div>',
    '                            </div>',
    '                            <button',
    '                                onClick={() => { setShowMeetModal(false); setMeetLink(null); setMeetError(\'\') }}',
    '                                className="w-8 h-8 rounded-xl bg-slate-100 hover:bg-slate-200 flex items-center justify-center transition text-slate-500"',
    '                            >✕</button>',
    '                        </div>',
    '',
    '                        <div className="px-6 py-5 space-y-4 max-h-[75vh] overflow-y-auto custom-scrollbar">',
    '                            {meetLink ? (',
    '                                /* ── SUCCESS STATE ── */',
    '                                <div className="flex flex-col items-center py-6 gap-4">',
    '                                    <div className="w-16 h-16 bg-emerald-100 rounded-3xl flex items-center justify-center">',
    '                                        <svg className="w-8 h-8 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">',
    '                                            <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />',
    '                                        </svg>',
    '                                    </div>',
    '                                    <div className="text-center">',
    '                                        <div className="text-lg font-black text-slate-800">Meet Created!</div>',
    '                                        <p className="text-sm text-slate-500 mt-1">Invites have been sent to all attendees.</p>',
    '                                    </div>',
    '                                    <div className="w-full bg-slate-50 border border-slate-200 rounded-2xl p-4 flex items-center gap-3">',
    '                                        <svg className="w-5 h-5 text-emerald-500 shrink-0" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">',
    '                                            <path strokeLinecap="round" strokeLinejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" />',
    '                                        </svg>',
    '                                        <span className="text-sm font-semibold text-blue-600 truncate flex-1">{meetLink}</span>',
    '                                        <button',
    '                                            onClick={() => { navigator.clipboard.writeText(meetLink) }}',
    '                                            className="shrink-0 text-xs font-bold text-slate-500 hover:text-blue-600 bg-white border border-slate-200 rounded-lg px-2.5 py-1 transition"',
    '                                        >Copy</button>',
    '                                    </div>',
    '                                    <a',
    '                                        href={meetLink}',
    '                                        target="_blank"',
    '                                        rel="noopener noreferrer"',
    '                                        className="w-full py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-sm rounded-xl flex items-center justify-center gap-2 transition shadow-sm shadow-emerald-200"',
    '                                    >',
    '                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth={2.5} viewBox="0 0 24 24">',
    '                                            <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />',
    '                                        </svg>',
    '                                        Open Meet',
    '                                    </a>',
    '                                </div>',
    '                            ) : (',
    '                                /* ── FORM STATE ── */',
    '                                <>',
    '                                    {/* Title */}',
    '                                    <div>',
    '                                        <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5">Meeting Title</label>',
    '                                        <input',
    '                                            value={meetTitle}',
    '                                            onChange={e => setMeetTitle(e.target.value)}',
    '                                            className="w-full px-4 py-2.5 text-sm bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition"',
    '                                            placeholder="e.g. Lead Discussion – Acme Corp"',
    '                                        />',
    '                                    </div>',
    '',
    '                                    {/* Date & Time */}',
    '                                    <div className="grid grid-cols-2 gap-3">',
    '                                        <div>',
    '                                            <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5">Date</label>',
    '                                            <input',
    '                                                type="date"',
    '                                                value={meetDate}',
    '                                                onChange={e => setMeetDate(e.target.value)}',
    '                                                className="w-full px-3 py-2.5 text-sm bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition"',
    '                                            />',
    '                                        </div>',
    '                                        <div>',
    '                                            <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5">Time</label>',
    '                                            <input',
    '                                                type="time"',
    '                                                value={meetTime}',
    '                                                onChange={e => setMeetTime(e.target.value)}',
    '                                                className="w-full px-3 py-2.5 text-sm bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition"',
    '                                            />',
    '                                        </div>',
    '                                    </div>',
    '',
    '                                    {/* Duration */}',
    '                                    <div>',
    '                                        <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Duration</label>',
    '                                        <div className="flex gap-2">',
    '                                            {[15, 30, 45, 60, 90].map(d => (',
    '                                                <button',
    '                                                    key={d}',
    '                                                    onClick={() => setMeetDuration(d)}',
    '                                                    className={`flex-1 py-2 rounded-xl text-xs font-bold transition border ${meetDuration === d',
    '                                                        ? \'bg-emerald-600 text-white border-emerald-600 shadow-sm\'',
    '                                                        : \'bg-slate-50 text-slate-600 border-slate-200 hover:border-emerald-400 hover:text-emerald-600\'',
    '                                                        }`}',
    '                                                >{d}m</button>',
    '                                            ))}',
    '                                        </div>',
    '                                    </div>',
    '',
    '                                    {/* Attendees */}',
    '                                    <div>',
    '                                        <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5">Attendee Emails</label>',
    '                                        <div className="flex gap-2">',
    '                                            <input',
    '                                                value={meetAttendeeInput}',
    '                                                onChange={e => { setMeetAttendeeInput(e.target.value); setMeetError(\'\') }}',
    '                                                onKeyDown={e => { if (e.key === \'Enter\' || e.key === \',\') { e.preventDefault(); handleAddMeetAttendee() } }}',
    '                                                placeholder="someone@example.com"',
    '                                                className="flex-1 px-3 py-2.5 text-sm bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition"',
    '                                            />',
    '                                            <button',
    '                                                onClick={handleAddMeetAttendee}',
    '                                                className="px-4 py-2.5 bg-slate-800 hover:bg-slate-700 text-white text-xs font-bold rounded-xl transition"',
    '                                            >Add</button>',
    '                                        </div>',
    '                                        <p className="text-[10px] text-slate-400 mt-1">Press Enter or comma to add multiple</p>',
    '',
    '                                        {/* Tags */}',
    '                                        {meetAttendees.length > 0 && (',
    '                                            <div className="flex flex-wrap gap-1.5 mt-2.5">',
    '                                                {meetAttendees.map(email => (',
    '                                                    <span key={email} className="inline-flex items-center gap-1.5 bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs font-semibold px-2.5 py-1 rounded-full">',
    '                                                        {email}',
    '                                                        <button onClick={() => handleRemoveMeetAttendee(email)} className="text-emerald-400 hover:text-red-500 transition font-black leading-none">×</button>',
    '                                                    </span>',
    '                                                ))}',
    '                                            </div>',
    '                                        )}',
    '                                    </div>',
    '',
    '                                    {/* Error */}',
    '                                    {meetError && (',
    '                                        <div className="flex items-center gap-2 text-red-600 text-xs font-semibold bg-red-50 border border-red-100 rounded-xl px-3 py-2.5">',
    '                                            <svg className="w-3.5 h-3.5 shrink-0" fill="none" stroke="currentColor" strokeWidth={3} viewBox="0 0 24 24">',
    '                                                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />',
    '                                            </svg>',
    '                                            {meetError}',
    '                                        </div>',
    '                                    )}',
    '                                </>',
    '                            )}',
    '                        </div>',
    '',
    '                        {/* Footer */}',
    '                        {!meetLink && (',
    '                            <div className="px-6 pb-6 pt-2 flex gap-3">',
    '                                <button',
    '                                    onClick={() => { setShowMeetModal(false); setMeetError(\'\') }}',
    '                                    className="flex-1 py-2.5 rounded-xl border border-slate-200 text-slate-600 font-semibold text-sm hover:bg-slate-50 transition"',
    '                                >Cancel</button>',
    '                                <button',
    '                                    onClick={handleGenerateMeet}',
    '                                    disabled={isMeetLoading}',
    '                                    className="flex-1 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 disabled:bg-slate-200 disabled:text-slate-400 text-white font-bold text-sm transition shadow-sm shadow-emerald-200 flex items-center justify-center gap-2"',
    '                                >',
    '                                    {isMeetLoading ? (',
    '                                        <><svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" /></svg>Generating...</>',
    '                                    ) : (',
    '                                        <><svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth={2.5} viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M15 10l4.553-2.069A1 1 0 0121 8.82v6.36a1 1 0 01-1.447.894L15 14M4 8a2 2 0 012-2h9a2 2 0 012 2v8a2 2 0 01-2 2H6a2 2 0 01-2-2V8z" /></svg>Generate Meet Link</>',
    '                                    )}',
    '                                </button>',
    '                            </div>',
    '                        )}',
    '                    </div>',
    '                </div>',
    '            )}',
    '        </div>',
    '    )',
    '}'
];

const newContent = truncated.concat(modalCode).join('\n');
fs.writeFileSync(path, newContent, 'utf8');
console.log('Successfully fixed Leads.jsx');
